runtime: python312
service: api
instance_class: F2

entrypoint: gunicorn -b :$PORT main:app

env_variables:
  FLASK_ENV: "production"
  FRONTEND_URL: "https://PROJECT_ID.uc.r.appspot.com"

automatic_scaling:
  min_instances: 1
  max_instances: 20
  target_cpu_utilization: 0.65

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

handlers:
- url: /api/internal/.*
  script: auto
  login: admin

- url: /.*
  script: auto
  secure: always
